# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/soleh/Code/NMR1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/soleh/Code/NMR1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/soleh/Code/NMR1/CMakeFiles /home/soleh/Code/NMR1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/soleh/Code/NMR1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NMR_exe

# Build rule for target.
NMR_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NMR_exe
.PHONY : NMR_exe

# fast build rule for target.
NMR_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/build
.PHONY : NMR_exe/fast

src/NmrRelaxationSolve.o: src/NmrRelaxationSolve.cpp.o
.PHONY : src/NmrRelaxationSolve.o

# target to build an object file
src/NmrRelaxationSolve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/NmrRelaxationSolve.cpp.o
.PHONY : src/NmrRelaxationSolve.cpp.o

src/NmrRelaxationSolve.i: src/NmrRelaxationSolve.cpp.i
.PHONY : src/NmrRelaxationSolve.i

# target to preprocess a source file
src/NmrRelaxationSolve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/NmrRelaxationSolve.cpp.i
.PHONY : src/NmrRelaxationSolve.cpp.i

src/NmrRelaxationSolve.s: src/NmrRelaxationSolve.cpp.s
.PHONY : src/NmrRelaxationSolve.s

# target to generate assembly for a file
src/NmrRelaxationSolve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/NmrRelaxationSolve.cpp.s
.PHONY : src/NmrRelaxationSolve.cpp.s

src/NmrRelaxationSolveKernels.o: src/NmrRelaxationSolveKernels.cu.o
.PHONY : src/NmrRelaxationSolveKernels.o

# target to build an object file
src/NmrRelaxationSolveKernels.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/NmrRelaxationSolveKernels.cu.o
.PHONY : src/NmrRelaxationSolveKernels.cu.o

src/NmrRelaxationSolveKernels.i: src/NmrRelaxationSolveKernels.cu.i
.PHONY : src/NmrRelaxationSolveKernels.i

# target to preprocess a source file
src/NmrRelaxationSolveKernels.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/NmrRelaxationSolveKernels.cu.i
.PHONY : src/NmrRelaxationSolveKernels.cu.i

src/NmrRelaxationSolveKernels.s: src/NmrRelaxationSolveKernels.cu.s
.PHONY : src/NmrRelaxationSolveKernels.s

# target to generate assembly for a file
src/NmrRelaxationSolveKernels.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/NmrRelaxationSolveKernels.cu.s
.PHONY : src/NmrRelaxationSolveKernels.cu.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NMR_exe.dir/build.make CMakeFiles/NMR_exe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NMR_exe"
	@echo "... src/NmrRelaxationSolve.o"
	@echo "... src/NmrRelaxationSolve.i"
	@echo "... src/NmrRelaxationSolve.s"
	@echo "... src/NmrRelaxationSolveKernels.o"
	@echo "... src/NmrRelaxationSolveKernels.i"
	@echo "... src/NmrRelaxationSolveKernels.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

